xcodeproj 'ZVideoRecorderExample.xcodeproj'

platform :ios, '6.0'

# ignore all warnings from all pods
inhibit_all_warnings!

pod 'PBJVision'
pod 'PBJVideoPlayer'
pod 'AFNetworking', '~> 1.3.3'
pod 'MBProgressHUD', '~> 0.8'